In [1]:
import numpy as np

### Array: It is used to create one-dimensional or multidimensional arrays from scratch

In [2]:
np.array([1,2,'$','Hello'])

array(['1', '2', '$', 'Hello'], dtype='<U11')

### linspace: Creates an array with evenly spaced float numbers over a specified interval


In [3]:
np.linspace(start=10, stop=100, num=10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Arange: Return evenly spaced integer values over a given interval with some step size.

In [4]:
np.arange(5,10,2)

array([5, 7, 9])

### Uniform: Generate a random sample from a uniform distribution between lower and higher limit values

In [5]:
np.random.uniform(5,10,size = 4)

array([5.76210049, 8.89490125, 7.59238713, 7.94059425])

### Random.randint: Generate n random integer samples within a range

In [6]:
np.random.randint(5,10,10)

array([8, 9, 7, 9, 6, 5, 7, 6, 5, 6])

### random: Generate n random float samples.

In [7]:
np.random.random(3)

array([0.94011157, 0.98985502, 0.22440276])

### Logspace: Generate evenly spaced numbers on a log scale.

In [8]:
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

### Zeros: Create an array of zeros

In [9]:
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

### Ones: Create an array of ones

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Full: Creates an n-dimensional array of a random value.

In [11]:
np.full(shape=(2,4),fill_value=2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

### Identity: Create an identity matrix with specified dimensions.

In [12]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])