In [1]:
import numpy as np

### Min: Return the minimum value from the array.

In [2]:
arr = np.array([10,100,1000,7])
np.min(arr)

7

### Max: Return the minimum value from the array.

In [17]:
arr = np.array([10,100,1000,7])
np.max(arr)

1000

### Unique: Return an array with all the unique elements sorted.

In [4]:
arr = np.array([10, 100, 100, 1000, 1000, 1000, 7,7,7,7,7])
np.unique(arr,return_counts=True)

(array([   7,   10,  100, 1000]), array([5, 1, 2, 3], dtype=int64))

### Mean: It is used to get the mean of the array.

In [5]:
arr = np.array([10,100,1000,7])
np.mean(arr,dtype='int')

279

### Median: It is used to get the median of the array.

In [6]:
arr = np.array([[100,200,300],[500,800,400]])
np.median(arr)

350.0

### Digitize: Return the indices of the bins(baskets) to which each value in the input array belongs

In [7]:
a = np.array([-1, 2, 6, 10, 3])
bins = np.array([0, 1, 2, 3, 10])
np.digitize(a,bins)

array([0, 3, 4, 5, 4], dtype=int64)

### Reshape: Returns an array containing the same data with a new shape.

In [8]:
arr_re = np.random.randint(15,size=(4,3))
arr_re

array([[ 0, 12, 13],
       [ 1, 11, 12],
       [ 9, 14,  4],
       [ 9, 14,  7]])

In [9]:
z = arr_re.reshape(3,4)
z

array([[ 0, 12, 13,  1],
       [11, 12,  9, 14],
       [ 4,  9, 14,  7]])

### Count Non-Zero: Count all the non-zero elements and return their count.

In [10]:
a = np.array([0,0,1,1,1,0])
np.count_nonzero(a)

3

### Argwhere: Find and return all the indices of non-zero elements.

In [11]:
a = np.array([0,0,1,1,1,0])
np.argwhere(a)

array([[2],
       [3],
       [4]], dtype=int64)

### Argmax & Argmin: Returns the index of the max & min element from the array.

In [12]:
arr = np.array([[0.12,0.64,0.19,0.05]])
np.argmax(arr)

1

In [13]:
np.argmin(arr)

3

### Squeeze: Reduce the dimension of an array by removing single-dimensional entries.

In [14]:
arr = np.array([[ 8],[14],[ 1],[ 8],[11],[ 4],[ 9],[ 4],[ 1],[13],[13],[11]])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11])

### Sort: Sort the array and return.kind: Sorting algorithm to use. {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’} 
### Abs: Return the absolute values of elements inside an array

In [16]:
arr = np.array([2,3,1,7,4,5])
np.sort(arr, kind=<>)

A = np.array([[1,-3,4],[-2,-4,3]])
np.abs(A)

SyntaxError: invalid syntax (3054818869.py, line 2)