In [1]:
import numpy as np

### np.intersect1d(arr1, arr2, assume_unique=False, return_indices=False) 
#### Return the sorted, unique values that are in both of the input arrays
#### <span style="color:red">assume_unique</span>: if true, then input arrays are both assumed to be unique which can speed up calculation.
#### <span style="color:red">return_indices</span>: if true, then common elements indices are returned.

In [2]:
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([3,4,5,8,9,1])
np.intersect1d(ar1,ar2)

array([1, 3, 4, 5])

In [3]:
np.intersect1d(ar1,ar2,return_indices=True)

(array([1, 3, 4, 5]),
 array([0, 2, 3, 4], dtype=int64),
 array([5, 0, 1, 2], dtype=int64))

### numpy.setdiff1d(ar1, ar2, assume_unique=False) 
#### Return the unique values in ar1 that are not in ar2
#### <span style="color:red">assume_unique</span>: if true, then input arrays are both assumed to be unique which can speed up calculation.

In [4]:
a = np.array([1, 7, 3, 2, 4, 1])
b = np.array([9, 2, 5, 6, 7, 8])
np.setdiff1d(a, b)

array([1, 3, 4])

### numpy.setxor1d(ar1, ar2, assume_unique=False) 
#### Return the sorted, unique values that are in only one (not both) of the input arrays.
#### <span style="color:red">assume_unique</span>: if true, then input arrays are both assumed to be unique which can speed up calculation.

In [5]:
a = np.array([1, 2, 3, 2, 4])
b = np.array([2, 3, 5, 7, 5])
np.setxor1d(a,b)

array([1, 4, 5, 7])

### numpy.union1d(ar1, ar2) 
#### Return the unique, sorted array of values that are in either of the two input arrays

In [6]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 5, 4, 36])
np.union1d(a,b)

array([ 1,  2,  3,  4,  5, 36])

### numpy.hsplit(ary, indices_or_sections)
#### Split an array into multiple sub-arrays horizontally (column-wise)

In [7]:
x = np.arange(16.0).reshape(4, 4)
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

### numpy.vsplit(ary, indices_or_sections)[source]
#### Split an array into multiple sub-arrays vertically (row-wise)

In [8]:
A = np.array([[3,4,5,2],[6,7,2,6]])
np.vsplit(A,2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

### numpy.hstack(tup)
#### Stack arrays in sequence horizontally (column wise)

In [9]:
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

### numpy.vstack(tup)
#### Stack arrays in sequence vertically (row wise).

In [10]:
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])